import torch.nn as nn
import torch.nn.functional as F

class VGG(nn.Module):
    def __init__(self,num_classes=200):
        super(VGG,self).__init__()
        self.conv1_1 = nn.Conv2d(3,64, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(64)
        self.conv1_2 = nn.Conv2d(64,64, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(64)
        self.maxpool1 = nn.MaxPool2d(2, stride=2)
        self.conv2_1 = nn.Conv2d(64,128, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn3 = nn.BatchNorm2d(128)
        self.conv2_2 = nn.Conv2d(128,128,kernel_size=3, stride=1, padding=1, bias=False)
        self.bn4 = nn.BatchNorm2d(128)
        self.maxpool2 = nn.MaxPool2d(2,stride=2)
        self.conv3_1 = nn.Conv2d(128,256, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn5 = nn.BatchNorm2d(256)
        self.conv3_2 = nn.Conv2d(256,256, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn6 = nn.BatchNorm2d(256)
        self.conv3_3 = nn.Conv2d(256,256, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn7 = nn.BatchNorm2d(256)
        self.maxpool3 = nn.MaxPool2d(2,stride=2)
        self.conv4_1 = nn.Conv2d(256,512, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn8 = nn.BatchNorm2d(512)
        self.conv4_2 = nn.Conv2d(512,512, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn9 = nn.BatchNorm2d(512)
        self.conv4_3 = nn.Conv2d(512,512, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn10 = nn.BatchNorm2d(512)
        self.maxpool4 = nn.MaxPool2d(2,stride=2)
        self.conv5_1 = nn.Conv2d(512,512, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn11 = nn.BatchNorm2d(512)
        self.conv5_2 = nn.Conv2d(512, 512, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn12 = nn.BatchNorm2d(512)
        self.conv5_3 = nn.Conv2d(512, 512, kernel_size=3, stride=1, padding=1, bias=False)
        self.bn13 = nn.BatchNorm2d(512)
        self.maxpool5 = nn.MaxPool2d(2,stride=2)
        self.flatten = nn.Flatten()
        self.fc1 = nn.Linear(8192, 4096)
        self.fc2 = nn.Linear(4096,4096)
        self.fc3 = nn.Linear(4096,200)
        self.dropout = nn.Dropout2d(p=0.5)



    def forward(self,x):
        out = F.relu(self.bn1(self.conv1_1(x)))
        out = F.relu(self.bn2(self.conv1_2(out)))
        out = self.maxpool1(out)
        out = F.relu(self.bn3(self.conv2_1(out)))
        out = F.relu(self.bn4(self.conv2_2(out)))
        out = self.maxpool2(out)
        out = F.relu(self.bn5(self.conv3_1(out)))
        out = F.relu(self.bn6(self.conv3_2(out)))
        out = F.relu(self.bn7(self.conv3_3(out)))
        out = self.maxpool3(out)
        out = F.relu(self.bn8(self.conv4_1(out)))
        out = F.relu(self.bn9(self.conv4_2(out)))
        out = F.relu(self.bn10(self.conv4_3(out)))
        out = self.maxpool4(out)
        out = F.relu(self.bn11(self.conv5_1(out)))
        out = F.relu(self.bn12(self.conv5_2(out)))
        out = F.relu(self.bn13(self.conv5_3(out)))
        out1 = self.maxpool5(out)
        out = self.flatten(out1)
        out = F.relu(self.fc1(out))
        out = self.dropout(out)
        out = F.relu(self.fc2(out))
        out = self.dropout(out)
        out = self.fc3(out)

        return out, out1